# Generated by Django 5.1.15 on 2026-07-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('cabello', 'Cabello'), ('unas', 'Uñas'), ('facial', 'Facial'), ('spa', 'Spa'), ('maquillaje', 'Maquillaje')], default='cabello', max_length=20)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popular', models.BooleanField(default=False, help_text='Se mostrará en "Servicios populares" (RF08)')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
